# Generated by Django 2.2.4 on 2019-09-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=200)),
                ('who', models.CharField(max_length=300)),
                ('when', models.DateField()),
                ('soc', models.IntegerField(default=0)),
                ('sem', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
    ]
