# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='who',
            field=models.CharField(max_length=300),
        ),
    ]
