# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-08 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_auto_20171013_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='sem',
            field=models.IntegerField(default=1),
        ),
    ]
